apiVersion: wrangle/v1
kind: Config
metadata: {}
spec:
  stores:
  - name: default
    type: azure.keyvault  
    properties:
      uri: https://clusterapi.vault.azure.net/
  env:
    AZURE_TENANT_ID: ((TenantID))
    AZURE_SUBSCRIPTION_ID: ((SubscriptionID))
    AZURE_CLIENT_ID: ((ClientID))
    AZURE_CLIENT_SECRET: ((ClientSecret))
  packages: []
