name: Deploy
on: 
  push:
    branches:
    - main

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    
    runs-on: ubuntu-latest
    environment: prod

    name: deploy
    steps:
      
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show