name: Deploy
on: 
  push:
    branches:
    - main
env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET:  ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_CLIENT_ID_USER_ASSIGNED_IDENTITY: ${{ secrets.AZURE_CLIENT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    steps:

    - uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Install clusterctl
      run: |
         curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.8.1/clusterctl-linux-amd64 -o clusterctl
         chmod +x clusterctl
         mv clusterctl /usr/local/bin/clusterctl

    - name: Bootstrap Management Cluster
      run: |
        sudo chmod +x ./scripts/*.sh
        ./scripts/apply.sh
